apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
    name: app-role
    namespace: webapps
rules:
    - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch 
        - extensions
        - policy
        - rbac.authorization.k8.io
      resources:
        - pods
        - componentsstatuses
        - configmaps
        - daemonsets
        - deployments
        - events
        - endpoints
        - horizontalpodautoscalers
        - ingress
        - jobs
        - limitranges
        - namespaces
        - nodes
        - secrets
        - pods
        - persistentvolumes
        - persistentvolumeclaims
        - resourcequotas
        - replicasets
        - replicationcontrollers
        - servicesaccounts
        - services
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
